# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('opendate', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('lastlogonDate', models.DateTimeField(verbose_name='last login')),
                ('userType', models.IntegerField(default=1)),
            ],
        ),
    ]
