# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCtpAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctpTradeIp', models.CharField(max_length=40)),
                ('ctpQuoteIp', models.CharField(max_length=40)),
                ('ctpTradePort', models.IntegerField(default=1)),
                ('ctpQuotePort', models.IntegerField(default=1)),
                ('ctpBroker', models.IntegerField(default=1)),
                ('ctpUserName', models.CharField(max_length=20)),
                ('ctpUserPassword', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='lastlogonDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='userctpaccount',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
    ]
